import mongoose from "mongoose";

const postSchema = mongoose.Schema(
	{
		postedBy: {
			type: mongoose.Schema.Types.ObjectId,
			ref: "User",
			required: true,
		},
		text: {
			type: String,
			maxLength: 500,
		},
		img: {
			type: String,
		},
		likes: {
			// array of user ids
			type: [mongoose.Schema.Types.ObjectId],
			ref: "User",
			default: [],
		},
		replies: [
			{
				userId: {
					type: mongoose.Schema.Types.ObjectId,
					ref: "User",
					required: true,
				},
				text: {
					type: String,
					required: true,
				},
				userProfilePic: {
					type: String,
				},
				username: {
					type: String,
				},
			},
		],
	},
	{
		timestamps: true,
	}
);

const Post = mongoose.model("Post", postSchema);

export default Post;


// import mongoose from "mongoose";

// const postSchema = mongoose.Schema(
//     {
//         postedBy: {
//             type: mongoose.Schema.Types.ObjectId,//this is gonna be an id that will be auto generated by mongoose
//             ref: 'User',// the reference of the above id will be User Model
//             required: true
//         },
//         text: {
//             type: String,
//             maxLength: 500
//         },
//         img: {
//             type: String,
//         },
//         likes: {
//             //Array of user ids
//             type: [mongoose.Schema.Types.ObjectId],
//             ref: 'User',
//             default: [],
//         },
//         //replies should be array of something so it is written as replies:[..]...

//         replies: [
//             {
//                 userId: {
//                     //as each replies should have a user id so to identify them
//                     type: mongoose.Schema.Types.ObjectId,
//                     ref: 'User',
//                     required: true
//                 },
//                 text: {
//                     type: String,
//                     required: true
//                 },

//                 userProfilePic: {
//                     type: String,
                    
//                 },
//                 username: {
//                     type: String,
//                     // required: true
//                 }
//             }
//         ]
//     }, {
//     timestamps: true
// }
// );

// const Post = mongoose.model("Post", postSchema);

// export default Post;
